# Netlify Build Configuration
[build]
  publish = "baconfort-react/dist"
  command = "cd baconfort-react && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://baconfort-react-2.onrender.com"

# Variables de entorno para el build
# VITE_API_URL configurada directamente en netlify.toml
